version: 3

output: prefixed

vars:

tasks:
  install-precommit:
    desc: Install pre-commit
    summary: Install the pre-commit package manager and hooks.
    cmds:
      - pip install pre-commit
      - pre-commit install --install-hooks --hook-type pre-commit --hook-type commit-msg
    status:
      - command -v pre-commit
      - test -f .git/hooks/commit-msg
      - test -f .git/hooks/pre-commit
    silent: true

  pre-commit:
    desc: Execute pre-commit
    summary: Execute all pre-commit hooks.
    deps:
      - install-precommit
    cmds:
      - pre-commit run -a

  unit-test:
    desc: Run unit tests
    summary: Run unit tests for a Lambda function.
    cmds:
      - poetry run pytest
    dir: '{{.USER_WORKING_DIR}}' # must 'cd' to Lambda dir first

  build:
    desc: Build a Lambda packages
    summary: Build a ZIP archive package for a Lambda function.
    cmds:
      - poetry build-lambda
    dir: '{{.USER_WORKING_DIR}}' # must 'cd' to Lambda dir first

  tf-init:
    desc: Initialize Terraform code
    summary: Executes a 'terraform init' to initializes the Terraform working directory.
    cmds:
      - terraform init -backend-config="./backend.config"
    dir: terraform/

  tf-plan:
    deps:
      - build
    desc: Show planned deployment
    summary: Executes a 'terraform plan' to show what resources would be deployed.
    cmds:
      - terraform plan
    dir: terraform/

  deploy:
    desc: Deploy resources
    summary: Applies Terraform code to deploy Lambdas and other resources to AWS.
    cmds:
      - terraform apply -auto-approve
    dir: terraform/
