version: 0.2

phases:
  install:
      runtime-versions:
        python: 3.13
      commands:
        - # install Poetry
        - # install Terraform
        - echo "install phase..."

  pre_build:
    commands:
      - # install Python packages via Poetry
      - echo "pre-build phase..."

  build:
    commands:
      - # run unit tests
      - # package Lambda function
      - # deploy
      - echo "Hello World!"
