version: 0.2

phases:
  install:
      runtime-versions:
        python: 3.13
      commands:
        - curl -sSL https://install.python-poetry.org | python3 -
        - /root/.local/bin/poetry --version
        - TF_ENV=$(<terraform/.terraform-version)
        - echo $TF_ENV

  pre_build:
    commands:
      - # install Python packages via Poetry
      - echo "pre-build phase..."

  build:
    commands:
      - # run unit tests
      - # package Lambda function
      - # deploy
      - echo "Hello World!"
