version: 0.2

phases:
  install:
      runtime-versions:
        python: 3.13
      commands:
        - which terraform || true
        - ls -latr
        - |
          curl -sSL https://install.python-poetry.org | python3 -
          /root/.local/bin/poetry --version
        - |
          TF_VER=$(<terraform/.terraform-version)
          cd /tmp
          curl -fsSL https://releases.hashicorp.com/terraform/${TF_VER}/terraform_${TF_VER}_linux_amd64.zip -o terraform.zip
          unzip terraform.zip
          chmod +x terraform
          mv terraform /usr/local/bin/
          rm terraform.zip
          cd $CODEBUILD_SRC_DIR
          terraform --version

  pre_build:
    commands:
      - # install Python packages via Poetry
      - echo "pre-build phase..."

  build:
    commands:
      - # run unit tests
      - # package Lambda function
      - # deploy
      - echo "Hello World!"
      - ls -latr

  post_build:
    commands:
      - ls -latr
